image: gradle:7.2-jdk11

stages:
  - build
  - test

build:
  stage: build
  script:
    - gradle build
  artifacts:
    paths:
      - build/distributions
    expire_in: 1 day
    when: always

cypress-test:
  image: registry.gitlab.com/sahajsoft/gurukul2022/csv-parser-srijan
  stage: test
  dependencies:
    - build
  script:
    - cd build/distributions
    - unzip csv-parser-srijan-1.0-SNAPSHOT.zip
    - sh csv-parser-srijan-1.0-SNAPSHOT/bin/csv-parser-srijan
    - echo "Server Started"
    - echo "Initiating Cypress Tests"
    - npm ci
    - npx cypress run --browser chrome


