stages:
  - build
  - test
  - deploy
#heroku:
#  stage: deploy
#  script:
#    - git remote remove origin
#    # - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/csv-parser-srijin.git
#    - git remote add origin https://gitlab.com/sahajsoft/gurukul2022/csv-parser-srijan.git


#    - git push heroku Deploy2:main

build:
  stage: build
  image: gradle:jdk11
  script:
    - gradle --no-daemon build
  artifacts:
    paths:
      - build/libs
    expire_in: 1 day
    when: always

junit-test:
  stage: test
  image: gradle:jdk11
  dependencies: []
  script:
    - gradle test
  timeout: 5m

# cypress-test:
#   stage: test
#   image: registry.gitlab.com/sahajsoft/gurukul2022/csv-parser-srijan:latestSrigin2
#   dependencies:
#     - build
#   script:
#     - unzip -q build/libs/csv-parser-srijan-1.0-SNAPSHOT.zip -d build/libs
#     - sh build/libs/csv-parser-srijan-1.0-SNAPSHOT/bin/csv-parser-srijan &
#     - npm install --save-dev cypress-file-upload
#     - npx cypress run

Heroku:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  script:
    - echo "Deploying ..."
    - docker login -u _ -p a5bcc214-2b4b-49cd-96cc-ff352e3c74f8 registry.heroku.com
    - docker build --file=Dockerfile --rm=true -t registry.heroku.com/csv-parser-srijin/web .
    - docker push registry.heroku.com/csv-parser-srijin/web
    - docker run -e HEROKU_API_KEY=$HEROKU_API_KEY wingrunr21/alpine-heroku-cli:latest container:release web -a csv-parser-srijin
    - echo "Backend Deployment Complete!"




