# Example config for CI/CD between Heroku and Gitlab by </unchained
image: node:latest

stages:
  - deploy

deploy:
  stage: deploy
  script:
    - apt-get update -qy
    - apt-get install -y ruby ruby-dev rubygems-integration
    - gem install dpl
    # Don't forget to define $HEROKU_APP and $HEROKU_API_KEY
    # variables under Settings > CI/CD > Secret Variables on GitLab
    - dpl --provider=heroku --app=$HEROKU_APP --api-key=$HEROKU_API_KEY --skip-cleanup