stages:
  - build
  - test
build:
  stage: build
  image: gradle:jdk11
  script:
    - gradle --no-daemon build
  artifacts:
    paths:
      - build/distributions
    expire_in: 1 day
    when: always

junit-test:
  stage: test
  image: gradle:jdk11
  dependencies: []
  script:
    - gradle test
  timeout: 5m

