stages:
  - build
build:
  image: docker:19.03.12
  stage: build
  services:
    - docker:19.03.12-dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t registry.gitlab.com/sahajsoft/gurukul2022/csv-parser-srijan:latestSrigin2 .
    - docker push $CI_REGISTRY/sahajsoft/gurukul2022/csv-parser-srijan:latestSrigin2