image: gradle:jdk11

stages:
  - build
  - test

build:
  stage: build
  script:
    - echo "Creating Jar for application."
    - - ./gradlew --no-daemon createJar
    - echo "Jar created successfully and stored in build/libs."
  artifacts:
    paths:
      - build/libs/csv-parser-srijan-1.0.jar
    expire_in: 1 day
  timeout: 5m

Junit-backend-test:
  stage: test
  dependencies:
    - build
  script:
    - echo "Initiating Tests"
    - gradle test
    - echo "All Tests Passed"

cypress-frontend-test:
  image: registry.gitlab.com/sahajsoft/gurukul2022/csv-parser-srijan
  stage: test
  dependencies:
    - build
  script:
    - echo "Initiating Cypress tests"
    - java -jar build/libs/csv-parser-srijan-1.0.jar &
    - npx cypress run
    - echo "All Cypress tests passed"
  timeout: 5m



