image: gradle:latest

stages:
  - build
  - test

build:
  stage: build
  script:
    - gradle --no-daemon build
  artifacts:
    paths:
      - build/distributions
    expire_in: 1 day
    when: always

unit-test:
  stage: test
  dependencies:
    - build
  script:
    - echo "Initiating Tests"
    - gradle test
    - echo "All Tests Passed"

cypress-test:
  image: cypress/browsers:node12.14.1-chrome85-ff81
  stage: test
  dependencies:
    - build
  script:
    - echo "Starting Server"
    - apt-get --allow-releaseinfo-change update
    - apt-get install -y default-jdk
    - ./gradlew build
    - ./gradlew run &
    - echo "Server Started"
    - echo "Initiating Cypress Tests"
    - npm ci
    - npm run start:ci &
    - npx cypress run --browser chrome
    - echo "All Tests Passed"


