image: gradle:7.2-jdk11

stages:
  - build
  - test

build:
  stage: build
  script:
    - gradle --no-daemon build
  artifacts:
    paths:
      - build/distributions
    expire_in: 1 day
    when: always

cypress-test:
  image: registry.gitlab.com/sahajsoft/gurukul2022/csv-parser-srijan
  stage: test
  dependencies:
    - build
  script:
    - unzip -q build/distributions/csv-parser-srijan-1.0-SNAPSHOT.zip -d build/distributions
    - sh build/distributions/csv-parser-srijan-1.0-SNAPSHOT/bin/csv-parser-srijan &
    - npm ci
    - npx cypress run --browser chrome


