stages:
  - build
  - build-docker-image
  - push-image-to-gitlab-registry

build:
  stage: build
  script:
    ./gradlew assemble
  artifacts:
    paths:
      - /home/gitlab-runner/

build-docker-image:
  stage: build-docker-image
  script:
    - docker info
    - docker build -t registry.gitlab.com/sahajsoft/gurukul2022/csv-parser-srijan .


Push Docker Image to GitLab Registry:
  stage: push-image-to-gitlab-registry
  before_script:
    - docker login registry.gitlab.com -u "utkarshs45" -p "glpat-xjNrtMUE3cJHibqRXSHy"
    - docker login registry.gitlab.com
  script:
    - docker info
    - docker push registry.gitlab.com/sahajsoft/gurukul2022/csv-parser-srijan