stages:
  - build
  - test
build:
  stage: build
  image: gradle:jdk11
  script:
    - gradle --no-daemon build
  artifacts:
    paths:
      - build/libs
    expire_in: 1 day
    when: always

junit-test:
  stage: test
  image: gradle:jdk11
  dependencies: []
  script:
    - gradle test
  timeout: 5m

cypress-test:
  stage: test
  image: registry.gitlab.com/sahajsoft/gurukul2022/csv-parser-srijan:latestSrigin2
  dependencies:
    - build
  script:
    - unzip -q build/libs/csv-parser-srijan-1.0-SNAPSHOT.zip -d build/libs
    - sh build/distributions/csv-parser-srijan-1.0-SNAPSHOT/bin/csv-parser-srijan &
    - npm install --save-dev cypress-file-upload 
    - npx cypress run