image: gradle:latest

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle


stages:
  - test

unit-test-job:
  stage: test
  script:
    - echo "Running unit tests."
    - gradle test

cypress-test-job:
  image: cypress/browsers:node12.14.1-chrome85-ff81
  stage: test
  script:
    - echo "Running cypress tests."
    - npm ci
    - npm run start:ci &
    - npx cypress run --browser chrome
